export { ChangePassword } from './change-password/ChangePassword'
export { ForgotPassword } from './forgot-password/ForgotPassword'
export { Login } from './login/Login'
export { Purchases } from './purchases/Purchases'
export { Sales} from './sales/Sales'
export { ValidateAccount } from './validate-account/ValidateAccount'
export { Warehouse } from './warehouse/Warehouse'
export { Access } from './access/Access'
export { Reports } from './reports/Reports'
export { Settings } from './settings/Settings'